# Basic sync workflow for the 
# https://ecpci-test.alcf.anl.gov/anl/llvmfork/llvmfork repository.
# 
# This action synch the main of the repository with the upstream 
# main.

name: Sync main branch @ANL with llvm/llvm-project

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync main
      run: |
        git clone -b $BRANCH https://$USERNAME:$REPO_KEY@$REPO $REPO_DIR
        cd $REPO_DIR
        git remote add upstream https://github.com/llvm/llvm-project.git
        git fetch upstream
        git merge upstream/main
        git push https://$USERNAME:$REPO_KEY@$REPO $BRANCH
      env: 
        REPO_KEY: ${{secrets.PAT_ANL}}
        USERNAME: ${{secrets.ANL_USERNAME}}
        REPO: ecpci-test.alcf.anl.gov/anl/llvmfork/llvmfork.git
        BRANCH: llvm.org/main
        REPO_DIR: llvm-project
