# This is a basic workflow to help you get started with Actions

name: Sync master branch with upstream

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        repository: llvm-doe-org/llvm-project
        token: ${{secrets.PAT_FOR_PUSH}}
    - name: Sync master
      run: | 
        git checkout master
        git remote add upstream https://github.com/llvm/llvm-project.git
        git fetch upstream
        git merge upstream/master
        git push https://$USERNAME:$REPO_KEY@github.com/llvm-doe-org/llvm-project.git $GITHUB_REF
      env: 
        REPO_KEY: ${{secrets.PAT_FOR_PUSH}}
        USERNAME: github-actions
