# Basic sync workflow for the llvm-doe-org/llvm-project repository.
# 
# This action synch the master of the repository with the upstream 
# master.

name: Sync master branch with llvm/llvm-project

on:
  schedule: # Run every 30 minutes
    - cron: '*/30 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: llvm-doe-org/llvm-project
        token: ${{secrets.PAT_FOR_PUSH}}
    - name: Sync master
      run: | 
        git checkout master
        git remote add upstream https://github.com/llvm/llvm-project.git
        git fetch upstream
        git merge upstream/master
        git push https://$USERNAME:$REPO_KEY@github.com/llvm-doe-org/llvm-project.git $GITHUB_REF
      env: 
        REPO_KEY: ${{secrets.PAT_FOR_PUSH}}
        USERNAME: github-actions
