# Basic sync workflow for the llvm-doe-org/llvm-project repository.
# 
# This action synch the main of the repository with the upstream 
# main.

name: Sync main branch with llvm/llvm-project

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: llvm-doe-org/llvm-project
        ref: llvm.org/main
        token: ${{secrets.PAT_FOR_PUSH}}
    - name: Sync main
      run: |
        git remote add upstream https://github.com/llvm/llvm-project.git
        git fetch upstream main
        git merge upstream/main
        git push https://$USERNAME:$REPO_KEY@github.com/llvm-doe-org/llvm-project.git llvm.org/main
      env: 
        REPO_KEY: ${{secrets.PAT_FOR_PUSH}}
        USERNAME: github-actions
